import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Mask and Bounding Box Overlay Generation\n",
                "This notebook generates image overlays. It intelligently loads an original image corresponding to a mask from `polyp_masks`, `instruments_masks`, `pseudo_masks`, or `gradcam_masks`.\n",
                "To preserve visual textures and colors, this tool draws the **contour outline** of the mask in green and a **bounding box** in red."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import cv2\n",
                "import os\n",
                "import glob\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "from pathlib import Path\n",
                "import csv\n",
                "import json\n",
                "\n",
                "DATA_DIR = r'D:\\FYP_MTL_GI_VQA\\data'\n",
                "IMAGES_DIR = os.path.join(DATA_DIR, 'images')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Overlay Function"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def get_original_image_path(mask_path):\n",
                "    \"\"\"Extracts the exact image ID from the mask's filename or parent directory and returns the path to the original image.\"\"\"\n",
                "    p = Path(mask_path)\n",
                "    img_id = None\n",
                "    \n",
                "    normalized_path = str(p.as_posix())\n",
                "    \n",
                "    if 'polyp_masks' in normalized_path or 'instruments_masks' in normalized_path:\n",
                "        img_id = p.stem\n",
                "    elif 'pseudo_masks' in normalized_path:\n",
                "        img_id = p.name.split('_')[0]\n",
                "    elif 'gradcam_masks' in normalized_path:\n",
                "        img_id = p.parent.name\n",
                "        \n",
                "    if img_id:\n",
                "        img_path = os.path.join(IMAGES_DIR, f\"{img_id}.jpg\")\n",
                "        if os.path.exists(img_path):\n",
                "            return img_path\n",
                "    return None\n",
                "\n",
                "def load_valid_instrument_ids():\n",
                "    valid_ids = set()\n",
                "    csv_path = r'D:\\FYP_MTL_GI_VQA\\data\\combined\\instruments_mask_phrases_v2.csv'\n",
                "    if os.path.exists(csv_path):\n",
                "        with open(csv_path, 'r', encoding='utf-8') as f:\n",
                "            reader = csv.DictReader(f)\n",
                "            for row in reader:\n",
                "                valid_ids.add(row['img_id'])\n",
                "    return valid_ids\n",
                "\n",
                "VALID_INSTRUMENT_IDS = load_valid_instrument_ids()\n",
                "\n",
                "def should_process_mask(mask_path):\n",
                "    p = Path(mask_path)\n",
                "    normalized_path = str(p.as_posix())\n",
                "    \n",
                "    if 'instruments_masks' in normalized_path:\n",
                "        img_id = p.stem\n",
                "        if img_id not in VALID_INSTRUMENT_IDS:\n",
                "            return False\n",
                "            \n",
                "    elif 'pseudo_masks' in normalized_path:\n",
                "        if 'cecum' not in p.name and 'z-line' not in p.name:\n",
                "            return False\n",
                "            \n",
                "    elif 'gradcam_masks' in normalized_path:\n",
                "        class_name = p.parent.parent.name\n",
                "        if class_name not in ['ulcerative_colitis', 'oesophagitis']:\n",
                "            return False\n",
                "        \n",
                "        bbox_json_path = p.parent / 'bbox_data.json'\n",
                "        if bbox_json_path.exists():\n",
                "            with open(bbox_json_path, 'r') as f:\n",
                "                bbox_data = json.load(f)\n",
                "                if bbox_data.get('prediction', 0) <= 0.80:\n",
                "                    return False\n",
                "        else:\n",
                "            return False\n",
                "            \n",
                "    return True\n",
                "\n",
                "def process_mask_and_image(mask_path, output_path=None, show=True):\n",
                "    if not should_process_mask(mask_path):\n",
                "        return\n",
                "    orig_img_path = get_original_image_path(mask_path)\n",
                "    if not orig_img_path:\n",
                "        print(f\"Original image not found for mask: {mask_path}\")\n",
                "        return\n",
                "        \n",
                "    img = cv2.imread(orig_img_path)\n",
                "    if img is None:\n",
                "        print(f\"Failed to read image: {orig_img_path}\")\n",
                "        return\n",
                "    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
                "    \n",
                "    mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)\n",
                "    if mask is None:\n",
                "        print(f\"Failed to read mask: {mask_path}\")\n",
                "        return\n",
                "        \n",
                "    _, binary_mask = cv2.threshold(mask, 127, 255, cv2.THRESH_BINARY)\n",
                "    contours, _ = cv2.findContours(binary_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)\n",
                "    \n",
                "    overlay = img.copy()\n",
                "    \n",
                "    for c in contours:\n",
                "        # Draw green contour line\n",
                "        cv2.drawContours(overlay, [c], -1, (0, 255, 0), thickness=2)\n",
                "        # Draw red bounding box\n",
                "        x, y, w, h = cv2.boundingRect(c)\n",
                "        cv2.rectangle(overlay, (x, y), (x + w, y + h), (255, 0, 0), thickness=2)\n",
                "        \n",
                "    if show:\n",
                "        plt.figure(figsize=(15, 5))\n",
                "        plt.subplot(1, 3, 1)\n",
                "        plt.imshow(img)\n",
                "        plt.title('Original Image')\n",
                "        plt.axis('off')\n",
                "        \n",
                "        plt.subplot(1, 3, 2)\n",
                "        plt.imshow(mask, cmap='gray')\n",
                "        plt.title('Mask')\n",
                "        plt.axis('off')\n",
                "        \n",
                "        plt.subplot(1, 3, 3)\n",
                "        plt.imshow(overlay)\n",
                "        plt.title('Overlayed Contours & BBox')\n",
                "        plt.axis('off')\n",
                "        \n",
                "        plt.tight_layout()\n",
                "        plt.show()\n",
                "        \n",
                "    if output_path:\n",
                "        overlay_rgb = cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR)\n",
                "        out_dir = os.path.dirname(output_path)\n",
                "        if out_dir:\n",
                "            os.makedirs(out_dir, exist_ok=True)\n",
                "        cv2.imwrite(output_path, overlay_rgb)\n",
                "        print(f\"Saved to {output_path}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Test Overlays Inline"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "example_polyp = [p for p in glob.glob(os.path.join(DATA_DIR, \"polyp_masks\", \"*.jpg\")) if should_process_mask(p)]\n",
                "example_instrument = [p for p in glob.glob(os.path.join(DATA_DIR, \"instruments_masks\", \"*.jpg\")) if should_process_mask(p)]\n",
                "example_pseudo = [p for p in glob.glob(os.path.join(DATA_DIR, \"pseudo_masks\", \"*.jpg\")) if should_process_mask(p)]\n",
                "example_gradcam = [p for p in glob.glob(os.path.join(DATA_DIR, \"gradcam_masks\", \"*\", \"*\", \"mask.png\")) if should_process_mask(p)]\n",
                "\n",
                "print(\"Testing Polyp Mask\")\n",
                "if example_polyp: process_mask_and_image(example_polyp[0])\n",
                "\n",
                "print(\"Testing Instrument Mask\")\n",
                "if example_instrument: process_mask_and_image(example_instrument[0])\n",
                "\n",
                "print(\"Testing Pseudo Mask (Cecum/Z-line)\")\n",
                "if example_pseudo: process_mask_and_image(example_pseudo[0])\n",
                "\n",
                "print(\"Testing Gradcam Mask\")\n",
                "if example_gradcam: process_mask_and_image(example_gradcam[0])"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Batch Processing Function"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def batch_process_folder(mask_folder, output_dest_folder, ext=\"*.jpg\"):\n",
                "    \"\"\"\n",
                "    Recursively process all masks in `mask_folder` and save overlays into `output_dest_folder`.\n",
                "    Usage: batch_process_folder(os.path.join(DATA_DIR, \"polyp_masks\"), os.path.join(DATA_DIR, \"overlayed_images/polyp\"))\n",
                "    \"\"\"\n",
                "    paths = glob.glob(os.path.join(mask_folder, \"**\", ext), recursive=True)\n",
                "    os.makedirs(output_dest_folder, exist_ok=True)\n",
                "    print(f\"Found {len(paths)} masks in {mask_folder}\")\n",
                "    for path in paths:\n",
                "        p = Path(path)\n",
                "        # Use original mask file stem to name the new overlay, e.g. `<img_id>_overlay.jpg`\n",
                "        out_filename = f\"{p.stem}_overlay.jpg\"\n",
                "        if p.name == \"mask.png\": \n",
                "            # For gradcam masks, use parent's id (img_id)\n",
                "            out_filename = f\"{p.parent.name}_overlay.jpg\"\n",
                "            \n",
                "        out_path = os.path.join(output_dest_folder, out_filename)\n",
                "        process_mask_and_image(path, output_path=out_path, show=False)\n",
                "    print(\"Batch processing completed.\")\n",
                "        "
            ]
        }
    ],
    "metadata": {},
    "nbformat": 4,
    "nbformat_minor": 5
}

with open(r"D:\FYP_MTL_GI_VQA\Create_Overlays.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)
